travis:
  secure:
    BINSTAR_TOKEN: IaBIoWjy/pgndwPgOj4XJMHVfQZN3R1Fk3stwMFdAoOe/2X38uF4EAYPlAeohSrqch8vbxvP8YfvC+A7twZxwLSmGbtR6avHbxF2CnNh+jn0xq97dmeqAFbUa8Bnv41CI8vUt5N3hoJ7O5Yo3h2Lej0Xu9pdlQL71Zl0Q+I7z7eju5L0eKUuRH/WQajP27RNXqP+pqwW+3HIjPDc738lpz3NuXPUO1iVNsxCPmBgNwQ1V57IurymklhxhYhFLSZkA1rXEezhKA6Rn5cupsVjtdiSwNLyXLrh34iffSXXx2KV16jZBYRrbil+5vb1HSbnVHHVHKuFC1dpLaZQ230luVsUsyEvbPS5TWSBhOslEXLABJ4d0bFJmgLe33dP44/i7EsmQZs5h/6e02k5A7CCM7OWhFNwr2DOMnvs7uEqPSBcEHWxq0CT9HZd5b3fvc/eCeIZlfbOA4DOGwZ+gk8DDIzIiM4njhknRhJHVYDTnYv/k8qd7bzbJKftQFbK2nom05nK1j5uDpkWKHnuufLTyTZf6oD3CXA/alEhGoEYhvpscr61qEinN6d9FRLiwffmvVh+Kiyc6F6raxltkHxvAYV+ccaPiKx7+wWQaCWo1oCItmcXMWzsP0UAdx1GaH3VqEDdgCxNJEZMZcsYLGqR5VmLXKlMPNc0I9D+BwSrmno=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
